trigger:
  branches:
    include:
      - main # Specify branch to trigger the pipeline

pool:
  name: "VM-Agent-Pool" # Use the name of your self-hosted agent pool
  demands: # Optional, add any specific requirements for your agent (e.g., Docker installed)
    - docker

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "6.x"

  - script: |
      dotnet build --configuration Release
      dotnet test --configuration Release
    displayName: "Build and Test"

  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: $(containerRegistry)/my-node-users-api
      Dockerfile: "**/Dockerfile"
      tags: |
        $(Build.BuildId)
