apiVersion: v1
kind: Service
metadata:
  name: my-node-users-api-service
spec:
  selector:
    app: my-node-users-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
